### ISSUE TITLE
RAMP/Websocket-to-TCP?

### ISSUE THREAD

**Issue by srzmnx** [WorldEditAxe/eaglerproxy#10]
Can I use this proxy in any way to connect to eaglercraft servers from java?

**Comment by WorldEditAxe** [comment]
with some modification, yes, you can. But at the moment probably not

**Comment by WorldEditAxe** [comment]
probably not - if a server owners/administration chooses to allow normal Minecraft clients to join their eaglercraft server, it's their choice (they just have to expose their bungee's vanilla server port to the internet)
not worth the time to implement something that can be enabled by changing server configs
