### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TechGeekUnited** [WorldEditAxe/eaglerproxy#11]
Was run on replit: 

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice 

up to date, audited 150 packages in 2s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 chmod u+x ./replit_launch.sh && ./replit_launch.sh
I 2023-06-08T00:02:35.288Z Launcher: Loading plugins...
I 2023-06-08T00:02:35.290Z PluginManager: Loading plugin metadata files...
I 2023-06-08T00:02:35.388Z PluginManager: Found 1 plugin(s): eagpaas@1.0.
I 2023-06-08T00:02:35.388Z PluginManager: Loading 1 plugin(s)...
(node:546) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
I 2023-06-08T00:02:35.789Z EaglerProxyAAS: Starting EaglerProxy as a Service v1.0.0...
I 2023-06-08T00:02:35.789Z EaglerProxyAAS: (internal server port: 25569, internal server IP: 25569)
I 2023-06-08T00:02:35.789Z EaglerProxyAAS: Starting internal server...
I 2023-06-08T00:02:35.877Z EaglerProxyAAS: Redirecting backend server IP... (this is required for the plugin to function)
I 2023-06-08T00:02:35.877Z PluginManager: Successfully loaded 1 plugin(s).
I 2023-06-08T00:02:35.877Z Launcher: Launching EaglerProxy...
I 2023-06-08T00:02:35.878Z EaglerProxy-0: Starting EaglerProxy v1.0.6...
I 2023-06-08T00:02:35.888Z SkinServer: Started EaglercraftX skin server.
I 2023-06-08T00:02:36.082Z EaglerProxy-0: Started WebSocket server and binded to 0.0.0.0 on port 8080.
W 2023-06-08T00:04:52.685Z EaglerProxy-InitialHandler: [InitialHandler] Error occurred whilst handling handshake: TypeError: Invalid packet ID detected!
    at CSLoginPacket.deserialize (file:///home/runner/eaglerproxy/build/proxy/packets/CSLoginPacket.js:32:19)
    at Proxy._handleWSConnection (file:///home/runner/eaglerproxy/build/proxy/Proxy.js:165:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
W 2023-06-08T00:05:00.093Z EaglerProxy-InitialHandler: [InitialHandler] Error occurred whilst handling handshake: TypeError: Invalid packet ID detected!
    at CSLoginPacket.deserialize (file:///home/runner/eaglerproxy/build/proxy/packets/CSLoginPacket.js:32:19)
    at Proxy._handleWSConnection (file:///home/runner/eaglerproxy/build/proxy/Proxy.js:165:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by WorldEditAxe** [comment]
eaglercraftx (1.8.9) only
