### ISSUE TITLE
Outdated Client

### ISSUE THREAD

**Issue by minidogg** [WorldEditAxe/eaglerproxy#12]
When I try connecting to the server it says: "Outdated Client" I tried configuring the version which didn't work. I tried installing ViaRewind which didn't work. I'm thinking the issue is the proxy.

**Comment by WorldEditAxe** [comment]
what version are you using?

**Comment by minidogg** [comment]
Client is 1.8.8 server is a local server running paper 1.9.4 with ViaRewind. I was originally using vanilla 1.8.8 but that told me outdated client so I tried updating to a newer version so I could use ViaRewind. And yes I was using the proxy and configured it. I would fix it my self because I know how to code in Node.js but I'm not to sure about how the eaglercraft and minecraft networking works.

**Comment by minidogg** [comment]
wait i think i know why its not working

**Comment by WorldEditAxe** [comment]
I'm pretty sure you're supposed to use ViaRewind with ViaVersion

**Comment by minidogg** [comment]
Thanks, I'll try to use both at the same time. Also thanks for telling me where to look for the code.

**Comment by minidogg** [comment]
It worked! Thank you!
