### ISSUE TITLE
how to do something

### ISSUE THREAD

**Issue by ironswordX-dev** [WorldEditAxe/eaglerproxy#18]
how would i set the default server that the proxy connects the client to?

**Comment by WorldEditAxe** [comment]
see `src/config,ts`, more specifically `config.adapter.host` and `config,adapter,port`
`config,bridge` is unused, you can remove it if you want to (server bridge is a separately installed plugin with a separate config file)

**Comment by ironswordX-dev** [comment]
i still dont understand

**Comment by WorldEditAxe** [comment]
go to that file `src/config.ts` in the project's folder and change the aforementioned settings to better accomodate your needs (`config.adapter.host` for changing the upstream server's ip, `config.adapter.port` for changing the port the server is located on)
