### ISSUE TITLE
"Username too short!"

### ISSUE THREAD

**Issue by EpixPlays** [WorldEditAxe/eaglerproxy#22]
Whenever I try to connect to my server, it says that my username is too short. My username is not too short as it is 9 characters and from what I see, you need 3 characters at least. Can someone help me?

**Comment by WorldEditAxe** [comment]
Clientsided issue, (probably) [not applicable to proxy](https://github.com/WorldEditAxe/eaglerproxy/blob/99b8d4ee3a01577182ea355e255773575f62aba1/src/proxy/Util.ts#L106]. What client were you using at the time?

**Comment by EpixPlays** [comment]
I was using a downloaded 1.8 eaglercraft client.

**Comment by WorldEditAxe** [comment]
What client version were you using? Please send me the client file, if possible.

**Comment by EpixPlays** [comment]
1.8.8
[Client](https://github.com/WorldEditAxe/eaglerproxy/files/12999192/h.zip)

**Comment by dxomg** [comment]
@EpixPlays I have tested your client, the issue you're facing is due to the client, its outdated

**Comment by WorldEditAxe** [comment]
They are probably right. Newer versions uses a custom handshake system which isn't compatible with the old one
