### ISSUE TITLE
Connection Lost: socketClosed

### ISSUE THREAD

**Issue by TrickTix** [WorldEditAxe/eaglerproxy#25]
I know this error is basically a wild card but I have no idea what is happening???

Whenever I try to join the server (which I am self hosting) through the EaglerProxy (which is on replit) I get this.

![Screenshot 2023-12-09 145814](https://github.com/WorldEditAxe/eaglerproxy/assets/95985704/c7cb5fed-f89f-4763-984f-4f7acd60e0a0)
![Screenshot 2023-12-09 145612](https://github.com/WorldEditAxe/eaglerproxy/assets/95985704/7b3c3435-a966-449c-a692-61172c00ba7a)

there are no errors on either end of the servers and no indication of what's happening. Also the server passthrough MOTD is working, but it has no connection?

![Screenshot 2023-12-09 152116](https://github.com/WorldEditAxe/eaglerproxy/assets/95985704/3ac4f3cf-5391-44ba-9e7b-e10454de1b0c)

**Comment by WorldEditAxe** [comment]
This is likely because your server is, for one reason or another, being abruptly disconnected by the upstream server. The error message suggests a low-level error, i.e., at the TCP level. Are you using any VPN blockers or any sort of server protection?
