### ISSUE TITLE
Doesn't work with latest EaglercraftX

### ISSUE THREAD

**Issue by Electronik21** [WorldEditAxe/eaglerproxy#28]
I tried to use this as a relay in EaglercraftX 1.8-u21 ultimate and it says no connection, and throws this error:
```
W 2024-01-28T20:53:51.077Z EaglerProxy-InitialHandler: [InitialHandler] Error occurred whilst handling handshake: TypeError: Invalid packet ID detected!
    at CSLoginPacket.deserialize (file:///opt/eaglerproxy/build/proxy/packets/CSLoginPacket.js:34:19)
    at Proxy._handleWSConnection (file:///opt/eaglerproxy/build/proxy/Proxy.js:176:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by WorldEditAxe** [comment]
I will get to working on this, but it is quite impractical to do so before u21's source code is released,

**Comment by Atticuss26** [comment]
Source code is now released.

**Comment by Atticuss26** [comment]
(in the Xbox Support server)

**Comment by WorldEditAxe** [comment]
apologies for the extremely late response (I was busy over the past month). Anyway, I could not reproduce this on u27. I suggest that you try again on another computer (or client) to rule out either one of those being the culprit.
