### ISSUE TITLE
suggestion: websocket to tcp

### ISSUE THREAD

**Issue by im-a-blobfish** [WorldEditAxe/eaglerproxy#3]
basically this but the opposite

actual eaglerxbungee releases in a few days so this in its current state will become obsolete

so i think a better idea would be to do this but the opposite, so it could be self hosted by users or made into a service like ayuns RAMP

**Comment by WorldEditAxe** [comment]
I agree with your proposal, but it would be better for it to be entirely rewritten as an EaglerX bungee plugin when it releases. While it is possible for the proxy to be converted to a bridge/relay server of some sort, providing a user-friendly (online) authentication system would require a lot of processing better suited for BungeeCord. However, I'll look into this suggestion, and see if I can repurpose the server.

**Comment by adamj454545** [comment]
I don't think it would work well as an eaglerxbungee plugin, here's why.

1) eaglerxbungee is already a plugin for modern bungeecord

2) it would work better as standalone so players can run it locally to join servers, and also replit server owners could run it on a separate repl to support java players as im pretty sure that replit only supports having one port open

**Comment by WorldEditAxe** [comment]
Can you provide a reference to where you got your information for #1, please?

**Comment by WorldEditAxe** [comment]
accepted (modular rewrite, contains TCP proxy/bidge plugin)
