### ISSUE TITLE
Running on replit crashes with error

### ISSUE THREAD

**Issue by zumbiepig** [WorldEditAxe/eaglerproxy#30]
I imported the repository into Replit, and it crashed when I ran it. However when I imported [this release](https://github.com/WorldEditAxe/eaglerproxy/releases/tag/EagPAAS-v1.2.1), it ran perfectly fine.

Sorry for the small text size, I had to fit everything in one screenshot.
![image](https://github.com/WorldEditAxe/eaglerproxy/assets/121742281/e36e2ce0-b674-4c5f-8e5f-beab61a10c56)

**Comment by WorldEditAxe** [comment]
this seems to be a dependency error on behalf of prismarinemc; I'll try updating and checking back

**Comment by WorldEditAxe** [comment]
I'll look into writing a workaround for this
