### ISSUE TITLE
daytime

### ISSUE THREAD

**Issue by FatalEagler** [WorldEditAxe/eaglerproxy#6]
can you make it so the times can change since it doesnt show if its day or night in the server
its just always night

**Comment by WorldEditAxe** [comment]
Can you please elaborate?

**Comment by ColdDev** [comment]
> can you make it so the times can change since it doesnt show if its day or night in the server its just always night

This sounds like it would be more relevant to the actual Bukkit/Spigot/Paper server as opposed to the Bungee proxy, or this WebSocket proxy in particular.

**Comment by vhcrack** [comment]
Go into your video settings and click the thing that says "24h day cycle" on
